global using Microsoft.AspNetCore.Mvc;
global using SurveyBasket.Api.Entities;
global using Mapster;
global using SurveyBasket.Api.Services;
global using FluentValidation;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SurveyBasket.Api.Contracts.Authentication;
global using SurveyBasket.Api.Contracts.Polls;
